image: golang:latest

stages:
  - build

build:
  stage: build
  script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go get -tags purego -d
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags purego -ldflags="-s -w" -o gosrvmon .

  artifacts:
    paths:
    - gosrvmon
